import { makeTerminal, makeTheme } from "../modules/themes.mjs";
import type { Accent, Mode, Scale, Tone } from "../modules/types.mjs";
import { accents, modes, tones } from "../modules/types.mjs";
import { hex } from "../modules/utilities.mjs";
import manifest from "../package.json" with { type: "json" };
import workbenchColors from "../schema/workbench_colors.json" with { type: "json" };

type WorkbenchColors = Partial<Record<keyof typeof workbenchColors.properties, string>>;

export const generateManifest = () => {
    const themes = [];

    for (const mode of modes) {
        for (const tone of tones) {
            for (const accent of accents) {
                themes.push({
                    label: `Airfoil ${mode} ${tone} ${accent}`,
                    mode: `${mode}`,
                    tone: `${tone}`,
                    accent: `${accent}`,
                    uiTheme: mode === "Light" ? "vs" : "vs-dark",
                    path: `./themes/airfoil-${mode.toLowerCase()}-${tone.toLowerCase()}-${accent.toLowerCase()}-color-theme.json`,
                });
            }
        }
    }

    return JSON.stringify(
        {
            ...manifest,
            contributes: {
                themes: [...themes],
            },
        },
        null,
        4,
    );
};

export const generateTerminal = (mode: Mode) => {
    const terminal = hex(makeTerminal(mode));

    const generatedTerminal = {
        name: `Airfoil ${mode}`,
        ...terminal,
    };

    return JSON.stringify(generatedTerminal, Object.keys(generatedTerminal).sort(), 4);
};

export const generateTheme = (mode: Mode, tone: Tone, accent: Accent) => {
    const createdTheme = makeTheme(mode, tone, accent);
    const { key, tw, terminal, theme } = {
        key: createdTheme.key,
        tw: createdTheme.tw,
        terminal: hex(createdTheme.terminal),
        theme: hex(createdTheme.theme),
    };
    const test = "#FF00FF";

    const colors: WorkbenchColors = {
        "activityBar.activeBackground": theme.transparent,
        "activityBar.activeBorder": theme.transparent,
        "activityBar.activeFocusBorder": theme.transparent,
        "activityBar.background": theme.background2,
        "activityBar.border": theme.border,
        "activityBar.dropBorder": theme.foreground,
        "activityBar.foreground": theme.foreground,
        "activityBar.inactiveForeground": theme.dim,
        "activityBarBadge.background": theme.foreground,
        "activityBarBadge.foreground": theme.background,
        "activityBarTop.activeBorder": theme.transparent,
        "activityBarTop.dropBorder": theme.foreground,
        "activityBarTop.foreground": theme.foreground,
        "activityBarTop.inactiveForeground": theme.dim,
        "badge.background": theme.foreground,
        "badge.foreground": theme.background,
        "banner.background": theme.focus,
        "banner.foreground": theme.foreground,
        "banner.iconForeground": theme.foreground,
        "breadcrumb.activeSelectionForeground": theme.foreground,
        "breadcrumb.background": theme.background,
        "breadcrumb.focusForeground": theme.foreground,
        "breadcrumb.foreground": theme.dim,
        "breadcrumbPicker.background": theme.background,
        "button.background": theme.focus,
        "button.border": theme.focus,
        "button.foreground": theme.foreground,
        "button.hoverBackground": theme.hover,
        "button.secondaryBackground": theme.focus,
        "button.secondaryForeground": theme.foreground,
        "button.secondaryHoverBackground": theme.hover,
        "button.separator": theme.border,
        "checkbox.background": theme.background,
        "checkbox.border": theme.border,
        "checkbox.foreground": theme.foreground,
        "checkbox.selectBackground": theme.background,
        "checkbox.selectBorder": theme.border,
        "commandCenter.activeBackground": theme.hover,
        "commandCenter.activeBorder": theme.hover,
        "commandCenter.activeForeground": theme.foreground,
        "commandCenter.background": theme.background,
        "commandCenter.border": theme.border,
        "commandCenter.debuggingBackground": theme.focus,
        "commandCenter.foreground": theme.foreground,
        "commandCenter.inactiveBorder": theme.border,
        "commandCenter.inactiveForeground": theme.foreground,
        "debugConsole.errorForeground": theme.error,
        "debugConsole.infoForeground": theme.accentColor,
        "debugConsole.sourceForeground": theme.comment,
        "debugConsole.warningForeground": theme.warning,
        "debugConsoleInputIcon.foreground": theme.foreground,
        "debugExceptionWidget.background": `${theme.error}40`,
        "debugExceptionWidget.border": theme.error,
        "debugIcon.breakpointCurrentStackframeForeground": tw.green[key.scale],
        "debugIcon.breakpointDisabledForeground": theme.dim,
        "debugIcon.breakpointForeground": tw.red[key.scale],
        "debugIcon.breakpointStackframeForeground": tw.red[key.scale],
        "debugIcon.breakpointUnverifiedForeground": theme.dim,
        "debugIcon.continueForeground": tw.blue[key.scale],
        "debugIcon.disconnectForeground": tw.red[key.scale],
        "debugIcon.pauseForeground": tw.blue[key.scale],
        "debugIcon.restartForeground": tw.green[key.scale],
        "debugIcon.startForeground": tw.green[key.scale],
        "debugIcon.stepBackForeground": tw.blue[key.scale],
        "debugIcon.stepIntoForeground": tw.blue[key.scale],
        "debugIcon.stepOutForeground": tw.blue[key.scale],
        "debugIcon.stepOverForeground": tw.blue[key.scale],
        "debugIcon.stopForeground": tw.red[key.scale],
        "debugToolBar.background": theme.background,
        "debugToolBar.border": theme.border,
        "debugView.exceptionLabelBackground": theme.background2,
        "debugView.exceptionLabelForeground": theme.foreground,
        "debugView.stateLabelBackground": theme.background2,
        "debugView.stateLabelForeground": theme.foreground,
        "debugView.valueChangedHighlight": tw.blue[key.scale],
        "descriptionForeground": theme.foreground,
        "disabledForeground": theme.dim,
        "dropdown.background": theme.background,
        "dropdown.border": theme.border,
        "dropdown.foreground": theme.foreground,
        "dropdown.listBackground": theme.background,
        "editor.background": theme.background,
        "editor.findMatchBackground": `${theme.accentColor}80`,
        "editor.findMatchBorder": theme.accentColor,
        "editor.findMatchHighlightBackground": `${theme.accentColor}80`,
        "editor.findMatchHighlightBorder": theme.accentColor,
        "editor.foreground": theme.foreground,
        "editor.lineHighlightBackground": theme.focus,
        "editor.lineHighlightBorder": theme.transparent,
        "editor.selectionBackground": `${theme.accentColor}40`,
        "editor.selectionForeground": theme.foreground,
        "editor.selectionHighlightBackground": theme.focus,
        "editor.selectionHighlightBorder": `${theme.success}59`,
        "editor.wordHighlightBackground": theme.transparent,
        "editor.wordHighlightBorder": `${theme.success}59`,
        "editor.wordHighlightStrongBackground": theme.transparent,
        "editor.wordHighlightStrongBorder": `${theme.success}59`,
        "editor.wordHighlightTextBackground": theme.transparent,
        "editor.wordHighlightTextBorder": `${theme.success}59`,
        "editorActiveLineNumber.foreground": theme.foreground,
        "editorBracketHighlight.foreground1": tw.orange[key.scale],
        "editorBracketHighlight.foreground2": tw.yellow[key.scale],
        "editorBracketHighlight.foreground3": tw.cyan[key.scale],
        "editorBracketHighlight.foreground4": tw.blue[key.scale],
        "editorBracketHighlight.foreground5": tw.purple[key.scale],
        "editorBracketHighlight.foreground6": tw.pink[key.scale],
        "editorBracketHighlight.unexpectedBracket.foreground": tw.red[key.scale],
        "editorBracketMatch.background": theme.transparent,
        "editorBracketMatch.border": theme.success,
        "editorBracketPairGuide.activeBackground1": theme.success,
        "editorBracketPairGuide.activeBackground2": theme.success,
        "editorBracketPairGuide.activeBackground3": theme.success,
        "editorBracketPairGuide.activeBackground4": theme.success,
        "editorBracketPairGuide.activeBackground5": theme.success,
        "editorBracketPairGuide.activeBackground6": theme.success,
        "editorBracketPairGuide.background1": tw.orange[key.scale],
        "editorBracketPairGuide.background2": tw.yellow[key.scale],
        "editorBracketPairGuide.background3": tw.cyan[key.scale],
        "editorBracketPairGuide.background4": tw.blue[key.scale],
        "editorBracketPairGuide.background5": tw.purple[key.scale],
        "editorBracketPairGuide.background6": tw.pink[key.scale],
        "editorCursor.background": theme.background,
        "editorCursor.foreground": theme.foreground,
        "editorGroup.border": theme.border,
        "editorGroup.dropBackground": theme.focus,
        "editorGroup.emptyBackground": theme.background,
        "editorGroupHeader.border": theme.transparent,
        "editorGroupHeader.noTabsBackground": theme.transparent,
        "editorGroupHeader.tabsBackground": theme.background2,
        "editorGroupHeader.tabsBorder": theme.transparent,
        "editorGutter.addedBackground": terminal.green,
        "editorGutter.background": theme.background,
        "editorGutter.deletedBackground": terminal.red,
        "editorGutter.foldingControlForeground": theme.foreground,
        "editorGutter.modifiedBackground": terminal.yellow,
        "editorIndentGuide.activeBackground": theme.success,
        "editorIndentGuide.activeBackground1": theme.success,
        "editorIndentGuide.activeBackground2": theme.success,
        "editorIndentGuide.activeBackground3": theme.success,
        "editorIndentGuide.activeBackground4": theme.success,
        "editorIndentGuide.activeBackground5": theme.success,
        "editorIndentGuide.activeBackground6": theme.success,
        "editorIndentGuide.background": theme.background2,
        "editorIndentGuide.background1": theme.background2,
        "editorIndentGuide.background2": theme.background2,
        "editorIndentGuide.background3": theme.background2,
        "editorIndentGuide.background4": theme.background2,
        "editorIndentGuide.background5": theme.background2,
        "editorIndentGuide.background6": theme.background2,
        "editorInlayHint.background": theme.background2,
        "editorInlayHint.foreground": theme.dim,
        "editorInlayHint.parameterBackground": theme.background2,
        "editorInlayHint.parameterForeground": theme.dim,
        "editorInlayHint.typeBackground": theme.background2,
        "editorInlayHint.typeForeground": theme.dim,
        "editorLineNumber.activeForeground": theme.foreground,
        "editorLineNumber.dimmedForeground": theme.dim,
        "editorLineNumber.foreground": theme.dim,
        "editorOverviewRuler.background": theme.transparent,
        "editorOverviewRuler.border": theme.transparent,
        "editorOverviewRuler.bracketMatchForeground": tw.green[key.scale],
        "editorOverviewRuler.deletedForeground": terminal.red,
        "editorOverviewRuler.errorForeground": theme.error,
        "editorOverviewRuler.findMatchForeground": `${theme.foreground}80`,
        "editorOverviewRuler.modifiedForeground": terminal.yellow,
        "editorOverviewRuler.selectionHighlightForeground": theme.foreground,
        "editorOverviewRuler.warningForeground": tw.yellow[key.scale],
        "editorPane.background": theme.background2,
        "editorRuler.foreground": theme.dim,
        "editorStickyScroll.background": theme.background,
        "editorStickyScroll.border": theme.border,
        "editorStickyScroll.shadow": theme.shadow,
        "editorStickyScrollHover.background": theme.hover,
        "editorUnicodeHighlight.background": theme.transparent,
        "editorUnicodeHighlight.border": terminal.red,
        "editorWidget.background": theme.background,
        "editorWidget.border": theme.border,
        "editorWidget.foreground": theme.foreground,
        "editorWidget.resizeBorder": theme.border,
        "errorForeground": theme.error,
        "extensionBadge.remoteBackground": theme.background2,
        "extensionBadge.remoteForeground": theme.foreground,
        "extensionButton.background": theme.focus,
        "extensionButton.foreground": theme.foreground,
        "extensionButton.hoverBackground": theme.hover,
        "extensionButton.prominentBackground": theme.focus,
        "extensionButton.prominentForeground": theme.foreground,
        "extensionButton.prominentHoverBackground": theme.hover,
        "extensionButton.separator": theme.border,
        "extensionIcon.preReleaseForeground": terminal.cyan,
        "extensionIcon.sponsorForeground": terminal.yellow,
        "extensionIcon.starForeground": terminal.yellow,
        "extensionIcon.verifiedForeground": terminal.green,
        "focusBorder": theme.transparent,
        "foreground": theme.foreground,
        "gitDecoration.addedResourceForeground": terminal.green,
        "gitDecoration.conflictingResourceForeground": terminal.purple,
        "gitDecoration.deletedResourceForeground": terminal.red,
        "gitDecoration.ignoredResourceForeground": theme.dim,
        "gitDecoration.modifiedResourceForeground": terminal.yellow,
        "gitDecoration.renamedResourceForeground": terminal.green,
        "gitDecoration.stageDeletedResourceForeground": terminal.red,
        "gitDecoration.stageModifiedResourceForeground": terminal.yellow,
        "gitDecoration.submoduleResourceForeground": terminal.blue,
        "gitDecoration.untrackedResourceForeground": terminal.green,
        "icon.foreground": theme.foreground,
        "input.background": theme.background,
        "input.border": theme.border,
        "input.foreground": theme.foreground,
        "input.placeholderForeground": theme.dim,
        "inputOption.activeBackground": theme.focus,
        "inputOption.activeBorder": theme.transparent,
        "inputOption.activeForeground": theme.foreground,
        "inputOption.hoverBackground": theme.hover,
        "keybindingLabel.background": theme.background2,
        "keybindingLabel.border": theme.border,
        "keybindingLabel.bottomBorder": theme.border,
        "keybindingLabel.foreground": theme.foreground,
        "keybindingTable.headerBackground": theme.focus,
        "keybindingTable.rowsBackground": theme.background2,
        "list.activeSelectionBackground": theme.focus,
        "list.activeSelectionForeground": theme.foreground,
        "list.activeSelectionIconForeground": theme.foreground,
        "list.deemphasizedForeground": theme.dim,
        "list.dropBackground": theme.focus,
        "list.dropBetweenBackground": theme.focus,
        "list.errorForeground": tw.red[key.scale],
        "list.filterMatchBackground": tw.green[key.scale],
        "list.filterMatchBorder": tw.green[key.scale],
        "list.focusAndSelectionOutline": theme.border,
        "list.focusBackground": theme.transparent,
        "list.focusForeground": theme.foreground,
        "list.focusHighlightForeground": theme.foreground,
        "list.focusOutline": theme.border,
        "list.highlightForeground": theme.foreground,
        "list.hoverBackground": theme.hover,
        "list.hoverForeground": theme.foreground,
        "list.inactiveFocusBackground": theme.transparent,
        "list.inactiveFocusOutline": theme.border,
        "list.inactiveSelectionBackground": theme.hover,
        "list.inactiveSelectionForeground": theme.foreground,
        "list.inactiveSelectionIconForeground": theme.foreground,
        "list.invalidItemForeground": tw.red[key.scale],
        "list.warningForeground": tw.yellow[key.scale],
        "listFilterWidget.background": theme.background,
        "listFilterWidget.noMatchesOutline": tw.red[key.scale],
        "listFilterWidget.outline": theme.border,
        "listFilterWidget.shadow": theme.shadow,
        "menu.background": theme.background,
        "menu.border": theme.border,
        "menu.foreground": theme.foreground,
        "menu.selectionBackground": theme.hover,
        "menu.selectionBorder": theme.transparent,
        "menu.selectionForeground": theme.foreground,
        "menu.separatorBackground": theme.border,
        "menubar.selectionBackground": theme.hover,
        "menubar.selectionBorder": theme.transparent,
        "menubar.selectionForeground": theme.foreground,
        "minimap.background": theme.transparent,
        "minimapSlider.activeBackground": theme.focus,
        "minimapSlider.background": theme.focus,
        "minimapSlider.hoverBackground": theme.hover,
        "notificationCenter.border": theme.border,
        "notificationCenterHeader.background": theme.background,
        "notificationCenterHeader.foreground": theme.foreground,
        "notificationLink.foreground": theme.accentColor,
        "notifications.background": theme.background,
        "notifications.border": theme.border,
        "notifications.foreground": theme.foreground,
        "notificationsErrorIcon.foreground": tw.red[key.scale],
        "notificationsInfoIcon.foreground": tw.amber[key.scale],
        "notificationsWarningIcon.foreground": tw.yellow[key.scale],
        "notificationToast.border": theme.border,
        "outputView.background": theme.background,
        "outputViewStickyScroll.background": theme.background,
        "panel.background": theme.background,
        "panel.border": theme.border,
        "panel.dropBorder": theme.foreground,
        "panelInput.border": theme.border,
        "panelSection.border": theme.border,
        "panelSection.dropBackground": theme.focus,
        "panelSectionHeader.background": theme.background,
        "panelSectionHeader.border": theme.border,
        "panelSectionHeader.foreground": theme.foreground,
        "panelTitle.activeBorder": theme.foreground,
        "panelTitle.activeForeground": theme.foreground,
        "panelTitle.inactiveForeground": theme.dim,
        "peekView.border": theme.border,
        "peekViewEditor.background": theme.background2,
        "peekViewEditor.matchHighlightBackground": theme.focus,
        "peekViewEditor.matchHighlightBorder": theme.transparent,
        "peekViewEditorGutter.background": theme.background2,
        "peekViewEditorStickyScroll.background": theme.background2,
        "peekViewResult.background": theme.background2,
        "peekViewResult.fileForeground": theme.foreground,
        "peekViewResult.lineForeground": theme.foreground,
        "peekViewResult.matchHighlightBackground": theme.focus,
        "peekViewResult.selectionBackground": theme.focus,
        "peekViewResult.selectionForeground": theme.foreground,
        "peekViewTitle.background": theme.focus,
        "peekViewTitleDescription.foreground": theme.foreground,
        "peekViewTitleLabel.foreground": theme.foreground,
        "pickerGroup.border": theme.border,
        "pickerGroup.foreground": theme.foreground,
        "quickInput.background": theme.background,
        "quickInput.foreground": theme.foreground,
        "quickInputList.focusBackground": theme.focus,
        "quickInputList.focusForeground": theme.foreground,
        "quickInputList.focusIconForeground": theme.foreground,
        "scrollbar.shadow": theme.shadow,
        "scrollbarSlider.activeBackground": theme.focus,
        "scrollbarSlider.background": theme.hover,
        "scrollbarSlider.hoverBackground": theme.hover,
        "search.resultsInfoForeground": tw.amber[key.scale],
        "selection.background": theme.focus,
        "settings.checkboxBackground": theme.background,
        "settings.checkboxBorder": theme.border,
        "settings.checkboxForeground": theme.foreground,
        "settings.dropdownBackground": theme.background,
        "settings.dropdownBorder": theme.border,
        "settings.dropdownForeground": theme.foreground,
        "settings.dropdownListBorder": theme.border,
        "settings.focusedRowBackground": theme.focus,
        "settings.focusedRowBorder": theme.border,
        "settings.headerBorder": theme.border,
        "settings.headerForeground": theme.foreground,
        "settings.modifiedItemIndicator": terminal.yellow,
        "settings.numberInputBackground": theme.background,
        "settings.numberInputBorder": theme.border,
        "settings.numberInputForeground": theme.foreground,
        "settings.rowHoverBackground": theme.hover,
        "settings.sashBorder": theme.border,
        "settings.settingsHeaderHoverForeground": theme.foreground,
        "settings.textInputBackground": theme.background,
        "settings.textInputBorder": theme.border,
        "settings.textInputForeground": theme.foreground,
        "sideBar.background": theme.background2,
        "sideBar.border": theme.border,
        "sideBar.dropBackground": theme.focus,
        "sideBar.foreground": theme.foreground,
        "sideBarSectionHeader.background": theme.background2,
        "sideBarSectionHeader.border": theme.border,
        "sideBarSectionHeader.foreground": theme.foreground,
        "sideBarTitle.foreground": theme.foreground,
        "sideBySideEditor.horizontalBorder": theme.border,
        "sideBySideEditor.verticalBorder": theme.border,
        "simpleFindWidget.sashBorder": theme.border,
        "statusBar.background": theme.background2,
        "statusBar.border": theme.border,
        "statusBar.debuggingBackground": theme.focus,
        "statusBar.debuggingBorder": theme.focus,
        "statusBar.debuggingForeground": theme.foreground,
        "statusBar.focusBorder": theme.focus,
        "statusBar.foreground": theme.foreground,
        "statusBar.noFolderBackground": theme.background,
        "statusBar.noFolderBorder": theme.border,
        "statusBar.noFolderForeground": theme.foreground,
        "statusBarItem.activeBackground": theme.focus,
        "statusBarItem.compactHoverBackground": theme.hover,
        "statusBarItem.focusBorder": theme.focus,
        "statusBarItem.hoverBackground": theme.hover,
        "statusBarItem.hoverForeground": theme.foreground,
        "symbolIcon.arrayForeground": tw.yellow[key.scale],
        "symbolIcon.booleanForeground": tw.yellow[key.scale],
        "symbolIcon.classForeground": tw.fuchsia[key.scale],
        "symbolIcon.colorForeground": theme.foreground,
        "symbolIcon.constantForeground": tw.yellow[key.scale],
        "symbolIcon.constructorForeground": tw.fuchsia[key.scale],
        "symbolIcon.enumeratorForeground": tw.fuchsia[key.scale],
        "symbolIcon.enumeratorMemberForeground": tw.blue[key.scale],
        "symbolIcon.eventForeground": tw.amber[key.scale],
        "symbolIcon.fieldForeground": tw.indigo[key.scale],
        "symbolIcon.fileForeground": theme.foreground,
        "symbolIcon.folderForeground": theme.foreground,
        "symbolIcon.functionForeground": tw.fuchsia[key.scale],
        "symbolIcon.interfaceForeground": tw.fuchsia[key.scale],
        "symbolIcon.keyForeground": tw.rose[key.scale],
        "symbolIcon.keywordForeground": tw.rose[key.scale],
        "symbolIcon.methodForeground": tw.fuchsia[key.scale],
        "symbolIcon.moduleForeground": tw.blue[key.scale],
        "symbolIcon.namespaceForeground": tw.fuchsia[key.scale],
        "symbolIcon.nullForeground": tw.red[key.scale],
        "symbolIcon.numberForeground": tw.purple[key.scale],
        "symbolIcon.objectForeground": tw.blue[key.scale],
        "symbolIcon.operatorForeground": tw.neutral[key.scale],
        "symbolIcon.packageForeground": tw.blue[key.scale],
        "symbolIcon.propertyForeground": tw.indigo[key.scale],
        "symbolIcon.referenceForeground": tw.blue[key.scale],
        "symbolIcon.snippetForeground": theme.foreground,
        "symbolIcon.stringForeground": tw.sky[key.scale],
        "symbolIcon.structForeground": tw.fuchsia[key.scale],
        "symbolIcon.textForeground": theme.foreground,
        "symbolIcon.typeParameterForeground": tw.blue[key.scale],
        "symbolIcon.unitForeground": tw.rose[key.scale],
        "symbolIcon.variableForeground": tw.blue[key.scale],
        "tab.activeBackground": theme.background,
        "tab.activeBorder": theme.transparent,
        "tab.activeBorderTop": theme.transparent,
        "tab.activeForeground": theme.foreground,
        "tab.activeModifiedBorder": theme.transparent,
        "tab.border": theme.border,
        "tab.dragAndDropBorder": theme.foreground,
        "tab.hoverBackground": theme.hover,
        "tab.hoverBorder": theme.transparent,
        "tab.hoverForeground": theme.foreground,
        "tab.inactiveBackground": theme.background2,
        "tab.inactiveForeground": theme.foreground,
        "tab.inactiveModifiedBorder": theme.transparent,
        "tab.lastPinnedBorder": theme.transparent,
        "tab.unfocusedActiveBackground": theme.transparent,
        "tab.unfocusedActiveBorder": theme.transparent,
        "tab.unfocusedActiveBorderTop": theme.transparent,
        "tab.unfocusedActiveForeground": theme.foreground,
        "tab.unfocusedActiveModifiedBorder": theme.transparent,
        "tab.unfocusedHoverBackground": theme.hover,
        "tab.unfocusedHoverBorder": theme.transparent,
        "tab.unfocusedHoverForeground": theme.foreground,
        "tab.unfocusedInactiveBackground": theme.transparent,
        "tab.unfocusedInactiveForeground": theme.foreground,
        "tab.unfocusedInactiveModifiedBorder": theme.transparent,
        "terminal.ansiBlack": terminal.black,
        "terminal.ansiBlue": terminal.blue,
        "terminal.ansiBrightBlack": terminal.brightBlack,
        "terminal.ansiBrightBlue": terminal.brightBlue,
        "terminal.ansiBrightCyan": terminal.brightCyan,
        "terminal.ansiBrightGreen": terminal.brightGreen,
        "terminal.ansiBrightMagenta": terminal.brightPurple,
        "terminal.ansiBrightRed": terminal.brightRed,
        "terminal.ansiBrightWhite": terminal.brightWhite,
        "terminal.ansiBrightYellow": terminal.brightYellow,
        "terminal.ansiCyan": terminal.cyan,
        "terminal.ansiGreen": terminal.green,
        "terminal.ansiMagenta": terminal.purple,
        "terminal.ansiRed": terminal.red,
        "terminal.ansiWhite": terminal.white,
        "terminal.ansiYellow": terminal.yellow,
        "terminal.background": theme.background,
        "terminal.border": theme.border,
        "terminal.dropBackground": theme.focus,
        "terminal.findMatchBackground": theme.focus,
        "terminal.findMatchBorder": theme.focus,
        "terminal.findMatchHighlightBackground": theme.border,
        "terminal.findMatchHighlightBorder": theme.border,
        "terminal.foreground": theme.foreground,
        "terminal.hoverHighlightBackground": theme.hover,
        "terminal.inactiveSelectionBackground": theme.hover,
        "terminal.selectionBackground": `${theme.accentColor}40`,
        "terminal.selectionForeground": theme.foreground,
        "terminal.tab.activeBorder": theme.transparent,
        "terminalCommandDecoration.defaultBackground": theme.foreground,
        "terminalCommandDecoration.errorBackground": tw.red[key.scale],
        "terminalCommandDecoration.successBackground": tw.green[key.scale],
        "terminalCursor.background": theme.transparent,
        "terminalCursor.foreground": theme.accentColor,
        "terminalOverviewRuler.cursorForeground": theme.foreground,
        "terminalOverviewRuler.findMatchForeground": tw.green[key.scale],
        "terminalStickyScroll.background": theme.background,
        "terminalStickyScrollHover.background": theme.background,
        "textLink.activeForeground": theme.accentColor,
        "textLink.foreground": theme.accentColor,
        "textSeparator.foreground": theme.border,
        "titleBar.activeBackground": theme.background2,
        "titleBar.activeForeground": theme.foreground,
        "titleBar.border": theme.border,
        "titleBar.inactiveBackground": theme.background2,
        "titleBar.inactiveForeground": theme.dim,
        "toolbar.activeBackground": theme.focus,
        "toolbar.hoverBackground": theme.hover,
        "toolbar.hoverOutline": theme.transparent,
        "tree.inactiveIndentGuidesStroke": tw[key.tone][mode === "Dark" ? 700 : 300],
        "tree.indentGuidesStroke": tw[key.tone][mode === "Dark" ? 600 : 400],
        "walkThrough.embeddedEditorBackground": theme.background,
        "walkthrough.stepTitle.foreground": theme.foreground,
        "welcomePage.background": theme.background,
        "welcomePage.progress.background": theme.background,
        "welcomePage.progress.foreground": theme.foreground,
        "welcomePage.tileBackground": theme.background2,
        "welcomePage.tileBorder": theme.border,
        "welcomePage.tileHoverBackground": theme.hover,
        "widget.border": theme.border,
        "widget.shadow": theme.shadow,

        // "editorOverviewRuler.addedForeground": test,
        // "editorOverviewRuler.commentForeground": test,
        // "editorOverviewRuler.commentUnresolvedForeground": test,
        // "editorOverviewRuler.commonContentForeground": test,
        // "editorOverviewRuler.currentContentForeground": test,
        // "editorOverviewRuler.incomingContentForeground": test,
        // "editorOverviewRuler.infoForeground": test,
        // "editorOverviewRuler.inlineChatInserted": test,
        // "editorOverviewRuler.inlineChatRemoved": test,
        // "editorOverviewRuler.rangeHighlightForeground": test,
        // "editorOverviewRuler.wordHighlightForeground": test,
        // "editorOverviewRuler.wordHighlightStrongForeground": test,
        // "editorOverviewRuler.wordHighlightTextForeground": test,
        // "actionBar.toggledBackground": test,
        // "charts.blue": test,
        // "charts.foreground": test,
        // "charts.green": test,
        // "charts.lines": test,
        // "charts.orange": test,
        // "charts.purple": test,
        // "charts.red": test,
        // "charts.yellow": test,
        // "chat.avatarBackground": test,
        // "chat.avatarForeground": test,
        // "chat.requestBackground": test,
        // "chat.requestBorder": test,
        // "chat.slashCommandBackground": test,
        // "chat.slashCommandForeground": test,
        // "commentsView.resolvedIcon": test,
        // "commentsView.unresolvedIcon": test,
        // "contrastActiveBorder": test,
        // "contrastBorder": test,
        // "debugTokenExpression.boolean": test,
        // "debugTokenExpression.error": test,
        // "debugTokenExpression.name": test,
        // "debugTokenExpression.number": test,
        // "debugTokenExpression.string": test,
        // "debugTokenExpression.value": test,
        // "diffEditor.border": test,
        // "diffEditor.diagonalFill": test,
        // "diffEditor.insertedLineBackground": test,
        // "diffEditor.insertedTextBackground": test,
        // "diffEditor.insertedTextBorder": test,
        // "diffEditor.move.border": test,
        // "diffEditor.moveActive.border": test,
        // "diffEditor.removedLineBackground": test,
        // "diffEditor.removedTextBackground": test,
        // "diffEditor.removedTextBorder": test,
        // "diffEditor.unchangedCodeBackground": test,
        // "diffEditor.unchangedRegionBackground": test,
        // "diffEditor.unchangedRegionForeground": test,
        // "diffEditor.unchangedRegionShadow": test,
        // "diffEditorGutter.insertedLineBackground": test,
        // "diffEditorGutter.removedLineBackground": test,
        // "diffEditorOverview.insertedForeground": test,
        // "diffEditorOverview.removedForeground": test,
        // "editor.findRangeHighlightBackground": test,
        // "editor.findRangeHighlightBorder": test,
        // "editor.focusedStackFrameHighlightBackground": test,
        // "editor.foldBackground": test,
        // "editor.hoverHighlightBackground": test,
        // "editor.inactiveSelectionBackground": test,
        // "editor.inlineValuesBackground": test,
        // "editor.inlineValuesForeground": test,
        // "editor.linkedEditingBackground": test,
        // "editor.rangeHighlightBackground": test,
        // "editor.rangeHighlightBorder": test,
        // "editor.snippetFinalTabstopHighlightBackground": test,
        // "editor.snippetFinalTabstopHighlightBorder": test,
        // "editor.snippetTabstopHighlightBackground": test,
        // "editor.snippetTabstopHighlightBorder": test,
        // "editor.stackFrameHighlightBackground": test,
        // "editor.symbolHighlightBackground": test,
        // "editor.symbolHighlightBorder": test,
        // "editorCodeLens.foreground": test,
        // "editorCommentsWidget.rangeActiveBackground": test,
        // "editorCommentsWidget.rangeBackground": test,
        // "editorCommentsWidget.replyInputBackground": test,
        // "editorCommentsWidget.resolvedBorder": test,
        // "editorCommentsWidget.unresolvedBorder": test,
        // "editorError.background": test,
        // "editorError.border": test,
        // "editorError.foreground": test,
        // "editorGhostText.background": test,
        // "editorGhostText.border": test,
        // "editorGhostText.foreground": test,
        // "editorGroup.dropIntoPromptBackground": test,
        // "editorGroup.dropIntoPromptBorder": test,
        // "editorGroup.dropIntoPromptForeground": test,
        // "editorGroup.focusedEmptyBorder": test,
        // "editorGutter.commentGlyphForeground": test,
        // "editorGutter.commentRangeForeground": test,
        // "editorGutter.commentUnresolvedGlyphForeground": test,
        // "editorHint.border": test,
        // "editorHint.foreground": test,
        // "editorHoverWidget.background": test,
        // "editorHoverWidget.border": test,
        // "editorHoverWidget.foreground": test,
        // "editorHoverWidget.highlightForeground": test,
        // "editorHoverWidget.statusBarBackground": test,
        // "editorInfo.background": test,
        // "editorInfo.border": test,
        // "editorInfo.foreground": test,
        // "editorLightBulb.foreground": test,
        // "editorLightBulbAi.foreground": test,
        // "editorLightBulbAutoFix.foreground": test,
        // "editorLink.activeForeground": test,
        // "editorMarkerNavigation.background": test,
        // "editorMarkerNavigationError.background": test,
        // "editorMarkerNavigationError.headerBackground": test,
        // "editorMarkerNavigationInfo.background": test,
        // "editorMarkerNavigationInfo.headerBackground": test,
        // "editorMarkerNavigationWarning.background": test,
        // "editorMarkerNavigationWarning.headerBackground": test,
        // "editorSuggestWidget.background": test,
        // "editorSuggestWidget.border": test,
        // "editorSuggestWidget.focusHighlightForeground": test,
        // "editorSuggestWidget.foreground": test,
        // "editorSuggestWidget.highlightForeground": test,
        // "editorSuggestWidget.selectedBackground": test,
        // "editorSuggestWidget.selectedForeground": test,
        // "editorSuggestWidget.selectedIconForeground": test,
        // "editorSuggestWidgetStatus.foreground": test,
        // "editorUnnecessaryCode.border": test,
        // "editorUnnecessaryCode.opacity": test,
        // "editorWarning.background": test,
        // "editorWarning.border": test,
        // "editorWarning.foreground": test,
        // "editorWatermark.foreground": test,
        // "editorWhitespace.foreground": test,
        // "inlineChat.background": test,
        // "inlineChat.border": test,
        // "inlineChat.regionHighlight": test,
        // "inlineChat.shadow": test,
        // "inlineChatDiff.inserted": test,
        // "inlineChatDiff.removed": test,
        // "inlineChatInput.background": test,
        // "inlineChatInput.border": test,
        // "inlineChatInput.focusBorder": test,
        // "inlineChatInput.placeholderForeground": test,
        // "inputValidation.errorBackground": test,
        // "inputValidation.errorBorder": test,
        // "inputValidation.errorForeground": test,
        // "inputValidation.infoBackground": test,
        // "inputValidation.infoBorder": test,
        // "inputValidation.infoForeground": test,
        // "inputValidation.warningBackground": test,
        // "inputValidation.warningBorder": test,
        // "inputValidation.warningForeground": test,
        // "interactive.activeCodeBorder": test,
        // "interactive.inactiveCodeBorder": test,
        // "merge.border": test,
        // "merge.commonContentBackground": test,
        // "merge.commonHeaderBackground": test,
        // "merge.currentContentBackground": test,
        // "merge.currentHeaderBackground": test,
        // "merge.incomingContentBackground": test,
        // "merge.incomingHeaderBackground": test,
        // "mergeEditor.change.background": test,
        // "mergeEditor.change.word.background": test,
        // "mergeEditor.changeBase.background": test,
        // "mergeEditor.changeBase.word.background": test,
        // "mergeEditor.conflict.handled.minimapOverViewRuler": test,
        // "mergeEditor.conflict.handledFocused.border": test,
        // "mergeEditor.conflict.handledUnfocused.border": test,
        // "mergeEditor.conflict.input1.background": test,
        // "mergeEditor.conflict.input2.background": test,
        // "mergeEditor.conflict.unhandled.minimapOverViewRuler": test,
        // "mergeEditor.conflict.unhandledFocused.border": test,
        // "mergeEditor.conflict.unhandledUnfocused.border": test,
        // "mergeEditor.conflictingLines.background": test,
        // "minimap.errorHighlight": test,
        // "minimap.findMatchHighlight": test,
        // "minimap.foregroundOpacity": test,
        // "minimap.infoHighlight": test,
        // "minimap.selectionHighlight": test,
        // "minimap.selectionOccurrenceHighlight": test,
        // "minimap.warningHighlight": test,
        // "minimapGutter.addedBackground": test,
        // "minimapGutter.deletedBackground": test,
        // "minimapGutter.modifiedBackground": test,
        // "multiDiffEditor.background": test,
        // "multiDiffEditor.border": test,
        // "multiDiffEditor.headerBackground": test,
        // "notebook.cellBorderColor": test,
        // "notebook.cellEditorBackground": test,
        // "notebook.cellHoverBackground": test,
        // "notebook.cellInsertionIndicator": test,
        // "notebook.cellStatusBarItemHoverBackground": test,
        // "notebook.cellToolbarSeparator": test,
        // "notebook.editorBackground": test,
        // "notebook.focusedCellBackground": test,
        // "notebook.focusedCellBorder": test,
        // "notebook.focusedEditorBorder": test,
        // "notebook.inactiveFocusedCellBorder": test,
        // "notebook.inactiveSelectedCellBorder": test,
        // "notebook.outputContainerBackgroundColor": test,
        // "notebook.outputContainerBorderColor": test,
        // "notebook.selectedCellBackground": test,
        // "notebook.selectedCellBorder": test,
        // "notebook.symbolHighlightBackground": test,
        // "notebookEditorOverviewRuler.runningCellForeground": test,
        // "notebookScrollbarSlider.activeBackground": test,
        // "notebookScrollbarSlider.background": test,
        // "notebookScrollbarSlider.hoverBackground": test,
        // "notebookStatusErrorIcon.foreground": test,
        // "notebookStatusRunningIcon.foreground": test,
        // "notebookStatusSuccessIcon.foreground": test,
        // "ports.iconRunningProcessForeground": test,
        // "problemsErrorIcon.foreground": test,
        // "problemsInfoIcon.foreground": test,
        // "problemsWarningIcon.foreground": test,
        // "profileBadge.background": test,
        // "profileBadge.foreground": test,
        // "progressBar.background": test,
        // "quickInput.list.focusBackground": test,
        // "quickInputTitle.background": test,
        // "sash.hoverBorder": test,
        // "scm.historyItemAdditionsForeground": test,
        // "scm.historyItemDeletionsForeground": test,
        // "scm.historyItemSelectedStatisticsBorder": test,
        // "scm.historyItemStatisticsBorder": test,
        // "searchEditor.findMatchBackground": test,
        // "searchEditor.findMatchBorder": test,
        // "searchEditor.textInputBorder": test,
        // "statusBarItem.errorBackground": test,
        // "statusBarItem.errorForeground": test,
        // "statusBarItem.errorHoverBackground": test,
        // "statusBarItem.errorHoverForeground": test,
        // "statusBarItem.offlineBackground": test,
        // "statusBarItem.offlineForeground": test,
        // "statusBarItem.offlineHoverBackground": test,
        // "statusBarItem.offlineHoverForeground": test,
        // "statusBarItem.prominentBackground": test,
        // "statusBarItem.prominentForeground": test,
        // "statusBarItem.prominentHoverBackground": test,
        // "statusBarItem.prominentHoverForeground": test,
        // "statusBarItem.remoteBackground": test,
        // "statusBarItem.remoteForeground": test,
        // "statusBarItem.remoteHoverBackground": test,
        // "statusBarItem.remoteHoverForeground": test,
        // "statusBarItem.warningBackground": test,
        // "statusBarItem.warningForeground": test,
        // "statusBarItem.warningHoverBackground": test,
        // "statusBarItem.warningHoverForeground": test,
        // "testing.coverCountBadgeBackground": test,
        // "testing.coverCountBadgeForeground": test,
        // "testing.coveredBackground": test,
        // "testing.coveredBorder": test,
        // "testing.coveredGutterBackground": test,
        // "testing.iconErrored": test,
        // "testing.iconFailed": test,
        // "testing.iconPassed": test,
        // "testing.iconQueued": test,
        // "testing.iconSkipped": test,
        // "testing.iconUnset": test,
        // "testing.message.error.decorationForeground": test,
        // "testing.message.error.lineBackground": test,
        // "testing.message.info.decorationForeground": test,
        // "testing.message.info.lineBackground": test,
        // "testing.messagePeekBorder": test,
        // "testing.messagePeekHeaderBackground": test,
        // "testing.peekBorder": test,
        // "testing.peekHeaderBackground": test,
        // "testing.runAction": test,
        // "testing.uncoveredBackground": test,
        // "testing.uncoveredBorder": test,
        // "testing.uncoveredBranchBackground": test,
        // "testing.uncoveredGutterBackground": test,
        // "textBlockQuote.background": test,
        // "textBlockQuote.border": test,
        // "textCodeBlock.background": test,
        // "textPreformat.background": test,
        // "textPreformat.foreground": test,
        // "tree.tableColumnsBorder": theme.border,
        // "tree.tableOddRowsBackground": theme.background2,
        // "window.activeBorder": test,
        // "window.inactiveBorder": test,
    };

    const generatedTheme = {
        $schema: "vscode://schemas/color-theme",
        name: `Airfoil ${mode} ${tone} ${accent}`,
        colors: { ...colors },
        tokenColors: [
            {
                scope: ["strong", "markup.bold", "markup.heading"],
                settings: { fontStyle: "bold" },
            },
            {
                scope: ["emphasis, markup.italic"],
                settings: { fontStyle: "italic" },
            },
            {
                scope: ["markup.underline"],
                settings: { fontStyle: "underline" },
            },
            {
                scope: ["markup.strikethrough"],
                settings: { fontStyle: "strikethrough" },
            },
            {
                scope: ["markup.inserted"],
                settings: { foreground: tw.green[key.scale] },
            },
            {
                scope: ["markup.deleted"],
                settings: { foreground: tw.red[key.scale] },
            },
            {
                scope: ["markup.changed"],
                settings: { foreground: tw.yellow[key.scale] },
            },
            {
                scope: ["comment", "comment.block", "comment.block.documentation", "comment.line"],
                settings: {
                    foreground: theme.comment,
                },
            },
            {
                scope: [
                    "constant",
                    "constant.character",
                    "constant.character.escape",
                    "constant.other",
                    "constant.regexp",
                    "constant.rgb-value",
                ],
                settings: {
                    foreground: tw.yellow[key.scale],
                },
            },
            {
                scope: [
                    "constant.numeric",
                    "constant.numeric.integer",
                    "constant.numeric.float",
                    "constant.numeric.hex",
                    "constant.numeric.octal",
                ],
                settings: {
                    foreground: tw.purple[key.scale],
                },
            },
            {
                scope: [
                    "entity",
                    "entity.name",
                    "entity.name.class",
                    "entity.name.function",
                    "entity.name.method",
                    "entity.name.section",
                    "entity.name.selector",
                    "entity.name.tag",
                    "entity.name.type",
                    "entity.other",
                    "entity.other.attribute-name",
                    "entity.other.inherited-class",
                    "punctuation.definition.heading",
                ],
                settings: {
                    foreground: tw.fuchsia[key.scale],
                },
            },
            {
                scope: ["invalid", "invalid.deprecated", "invalid.illegal"],
                settings: {
                    foreground: tw.red[key.scale],
                },
            },
            {
                scope: ["keyword", "keyword.control", "keyword.other", "string.json"],
                settings: {
                    foreground: tw.rose[key.scale],
                },
            },
            {
                scope: [
                    "keyword.operator",
                    "keyword.operator.new",
                    "keyword.operator.assignment",
                    "keyword.operator.arithmetic",
                    "keyword.operator.logical",
                ],
                settings: {
                    foreground: tw.neutral[key.scale],
                },
            },
            {
                scope: [
                    "meta",
                    "meta.block",
                    "meta.cast",
                    "meta.class",
                    "meta.function",
                    "meta.function-call",
                    "meta.preprocessor",
                    "meta.return-type",
                    "meta.selector",
                    "meta.tag",
                    "meta.type.annotation",
                    "meta.type",
                ],
                settings: {
                    foreground: tw.indigo[key.scale],
                },
            },
            {
                scope: [
                    "punctuation.definition.string.begin",
                    "punctuation.definition.string.end",
                    "punctuation.separator",
                    "punctuation.separator.continuation",
                    "punctuation.terminator",
                ],
                settings: {
                    foreground: tw.neutral[key.scale],
                },
            },
            {
                scope: ["storage", "storage.modifier", "storage.type"],
                settings: {
                    foreground: tw.green[key.scale],
                },
            },
            {
                scope: [
                    "string",
                    "string.interpolated",
                    "string.other",
                    "string.quoted",
                    "string.quoted.double",
                    "string.quoted.other",
                    "string.quoted.single",
                    "string.quoted.triple",
                    "string.regexp",
                    "string.unquoted",
                ],
                settings: {
                    foreground: tw.sky[key.scale],
                },
            },
            {
                scope: [
                    "support",
                    "support.class",
                    "support.constant",
                    "support.function",
                    "support.other",
                    "support.type",
                    "support.type.property-name",
                    "support.variable",
                ],
                settings: {
                    foreground: tw.amber[key.scale],
                },
            },
            {
                scope: [
                    "variable",
                    "variable.language",
                    "variable.name",
                    "variable.other",
                    "variable.other.readwrite",
                    "variable.parameter",
                ],
                settings: {
                    foreground: tw.blue[key.scale],
                },
            },
        ],
        semanticTokenColors: {
            newOperator: tw.purple[key.scale],
            stringLiteral: tw.red[key.scale],
            customLiteral: tw.yellow[key.scale],
            numberLiteral: tw.emerald[key.scale],
        },
    };

    return JSON.stringify(generatedTheme, null, 4);
};
