import resolveConfig from "tailwindcss/resolveConfig.js";
import type { DefaultColors } from "tailwindcss/types/generated/colors";
import tailwindConfig from "../tailwind.config";

const tw = resolveConfig(tailwindConfig).theme.colors;

export enum Mode {
    Dark,
    Light,
}

const test = tw.pink[400];

const terminalColors = (mode: Mode): Terminal => {
    switch (mode) {
        case Mode.Dark:
            return {
                black: tw.neutral[500],
                blue: tw.blue[500],
                brightBlack: tw.neutral[400],
                brightBlue: tw.blue[400],
                brightCyan: tw.cyan[400],
                brightGreen: tw.green[400],
                brightMagenta: tw.pink[400],
                brightRed: tw.red[400],
                brightWhite: tw.neutral[400],
                brightYellow: tw.yellow[400],
                cyan: tw.cyan[500],
                green: tw.green[500],
                magenta: tw.pink[500],
                red: tw.red[500],
                white: tw.neutral[500],
                yellow: tw.yellow[500],
            };
        case Mode.Light:
            return {
                black: tw.neutral[700],
                blue: tw.blue[700],
                brightBlack: tw.neutral[600],
                brightBlue: tw.blue[600],
                brightCyan: tw.cyan[600],
                brightGreen: tw.green[600],
                brightMagenta: tw.pink[600],
                brightRed: tw.red[600],
                brightWhite: tw.neutral[600],
                brightYellow: tw.yellow[600],
                cyan: tw.cyan[700],
                green: tw.green[700],
                magenta: tw.pink[700],
                red: tw.red[700],
                white: tw.neutral[700],
                yellow: tw.yellow[700],
            };
    }
};

export const themeColors = (mode: Mode, tone: string, accent: string): Theme => {
    switch (mode) {
        case Mode.Dark:
            return {
                name: "Airfoil Dark",
                mode: Mode.Dark,
                background: `${tw[tone as keyof DefaultColors][900]}`,
                background2: `${tw[tone as keyof DefaultColors][800]}`,
                border: `${tw[tone as keyof DefaultColors][700]}`,
                comment: tw.emerald[400],
                dim: `${tw[tone as keyof DefaultColors][500]}`,
                focus: `${tw[accent as keyof DefaultColors][800]}4D`,
                foreground: `${tw[tone as keyof DefaultColors][300]}`,
                hover: `${tw[accent as keyof DefaultColors][800]}33`,
                scale: 300,
                shadow: "#00000033",
                transparent: "#00000000",
                terminal: terminalColors(Mode.Dark),
            };
        case Mode.Light:
            return {
                name: "Airfoil Light",
                mode: Mode.Light,
                background: `${tw[tone as keyof DefaultColors][100]}`,
                background2: `${tw[tone as keyof DefaultColors][200]}`,
                border: `${tw[tone as keyof DefaultColors][300]}`,
                comment: tw.emerald[700],
                dim: `${tw[tone as keyof DefaultColors][500]}`,
                focus: `${tw[accent as keyof DefaultColors][300]}4D`,
                foreground: `${tw[tone as keyof DefaultColors][700]}`,
                hover: `${tw[accent as keyof DefaultColors][300]}33`,
                scale: 700,
                shadow: "#00000033",
                transparent: "#FFFFFF00",
                terminal: terminalColors(Mode.Light),
            };
    }
};

export const terminal = (theme: Theme) => {
    return {
        background: theme.background.toUpperCase(),
        black: theme.terminal.black.toUpperCase(),
        blue: theme.terminal.blue.toUpperCase(),
        brightBlack: theme.terminal.brightBlack.toUpperCase(),
        brightBlue: theme.terminal.brightBlue.toUpperCase(),
        brightCyan: theme.terminal.brightCyan.toUpperCase(),
        brightGreen: theme.terminal.brightGreen.toUpperCase(),
        brightPurple: theme.terminal.brightMagenta.toUpperCase(),
        brightRed: theme.terminal.brightRed.toUpperCase(),
        brightWhite: theme.terminal.brightWhite.toUpperCase(),
        brightYellow: theme.terminal.brightYellow.toUpperCase(),
        cursorColor: theme.foreground.toUpperCase(),
        cyan: theme.terminal.cyan.toUpperCase(),
        foreground: theme.foreground.toUpperCase(),
        green: theme.terminal.green.toUpperCase(),
        name: theme.name,
        purple: theme.terminal.magenta.toUpperCase(),
        red: theme.terminal.red.toUpperCase(),
        selectionBackground: theme.dim.toUpperCase(),
        white: theme.terminal.white.toUpperCase(),
        yellow: theme.terminal.yellow.toUpperCase(),
    };
};

export default (theme: Theme) => {
    return {
        $schema: "vscode://schemas/color-theme",
        name: theme.name,
        semanticHighlighting: true,
        colors: {
            "activityBar.activeBackground": theme.transparent,
            "activityBar.activeBorder": theme.transparent,
            "activityBar.activeFocusBorder": theme.transparent,
            "activityBar.background": theme.background2,
            "activityBar.border": theme.border,
            "activityBar.dropBorder": theme.foreground,
            "activityBar.foreground": theme.foreground,
            "activityBar.inactiveForeground": theme.dim,
            "activityBarBadge.background": theme.foreground,
            "activityBarBadge.foreground": theme.background,
            "activityBarTop.activeBorder": theme.transparent,
            "activityBarTop.dropBorder": theme.foreground,
            "activityBarTop.foreground": theme.foreground,
            "activityBarTop.inactiveForeground": theme.dim,
            "badge.background": theme.foreground,
            "badge.foreground": theme.background,
            "banner.background": theme.focus,
            "banner.foreground": theme.foreground,
            "banner.iconForeground": theme.foreground,
            "breadcrumb.activeSelectionForeground": theme.foreground,
            "breadcrumb.background": theme.background,
            "breadcrumb.focusForeground": theme.foreground,
            "breadcrumb.foreground": theme.dim,
            "breadcrumbPicker.background": theme.background,
            "button.background": theme.focus,
            "button.border": theme.focus,
            "button.foreground": theme.foreground,
            "button.hoverBackground": theme.hover,
            "button.secondaryBackground": theme.focus,
            "button.secondaryForeground": theme.foreground,
            "button.secondaryHoverBackground": theme.hover,
            "button.separator": theme.border,
            "checkbox.background": theme.background,
            "checkbox.border": theme.border,
            "checkbox.foreground": theme.foreground,
            "checkbox.selectBackground": theme.background,
            "checkbox.selectBorder": theme.border,
            "commandCenter.activeBackground": theme.hover,
            "commandCenter.activeBorder": theme.hover,
            "commandCenter.activeForeground": theme.foreground,
            "commandCenter.background": theme.background,
            "commandCenter.border": theme.border,
            "commandCenter.debuggingBackground": theme.focus,
            "commandCenter.foreground": theme.foreground,
            "commandCenter.inactiveBorder": theme.border,
            "commandCenter.inactiveForeground": theme.foreground,
            "dropdown.background": theme.background,
            "dropdown.border": theme.border,
            "dropdown.foreground": theme.foreground,
            "dropdown.listBackground": theme.background,
            "editor.background": theme.background,
            "editor.foreground": theme.foreground,
            "editor.lineHighlightBackground": theme.focus,
            "editor.lineHighlightBorder": theme.transparent,
            "editor.selectionBackground": theme.focus,
            "editor.selectionForeground": theme.foreground,
            "editor.selectionHighlightBackground": theme.focus,
            "editor.selectionHighlightBorder": theme.border,
            "editorActiveLineNumber.foreground": theme.foreground,
            "editorBracketHighlight.foreground1": tw.orange[theme.scale],
            "editorBracketHighlight.foreground2": tw.yellow[theme.scale],
            "editorBracketHighlight.foreground3": tw.cyan[theme.scale],
            "editorBracketHighlight.foreground4": tw.blue[theme.scale],
            "editorBracketHighlight.foreground5": tw.purple[theme.scale],
            "editorBracketHighlight.foreground6": tw.pink[theme.scale],
            "editorBracketHighlight.unexpectedBracket.foreground": tw.red[theme.scale],
            "editorBracketMatch.background": theme.transparent,
            "editorBracketMatch.border": tw.green[400],
            "editorBracketPairGuide.activeBackground1": tw.green[400],
            "editorBracketPairGuide.activeBackground2": tw.green[400],
            "editorBracketPairGuide.activeBackground3": tw.green[400],
            "editorBracketPairGuide.activeBackground4": tw.green[400],
            "editorBracketPairGuide.activeBackground5": tw.green[400],
            "editorBracketPairGuide.activeBackground6": tw.green[400],
            "editorBracketPairGuide.background1": tw.orange[theme.scale],
            "editorBracketPairGuide.background2": tw.yellow[theme.scale],
            "editorBracketPairGuide.background3": tw.cyan[theme.scale],
            "editorBracketPairGuide.background4": tw.blue[theme.scale],
            "editorBracketPairGuide.background5": tw.purple[theme.scale],
            "editorBracketPairGuide.background6": tw.pink[theme.scale],
            "editorCursor.background": theme.background,
            "editorCursor.foreground": theme.foreground,
            "editorGroup.border": theme.border,
            "editorGroup.dropBackground": theme.focus,
            "editorGroup.emptyBackground": theme.background,
            "editorGroupHeader.border": theme.transparent,
            "editorGroupHeader.noTabsBackground": theme.transparent,
            "editorGroupHeader.tabsBackground": theme.background2,
            "editorGroupHeader.tabsBorder": theme.transparent,
            "editorGutter.addedBackground": theme.terminal.green,
            "editorGutter.background": theme.background,
            "editorGutter.deletedBackground": theme.terminal.red,
            "editorGutter.foldingControlForeground": theme.foreground,
            "editorGutter.modifiedBackground": theme.terminal.yellow,
            "editorIndentGuide.activeBackground": tw.green[400],
            "editorIndentGuide.activeBackground1": tw.green[400],
            "editorIndentGuide.activeBackground2": tw.green[400],
            "editorIndentGuide.activeBackground3": tw.green[400],
            "editorIndentGuide.activeBackground4": tw.green[400],
            "editorIndentGuide.activeBackground5": tw.green[400],
            "editorIndentGuide.activeBackground6": tw.green[400],
            "editorIndentGuide.background": theme.background2,
            "editorIndentGuide.background1": theme.background2,
            "editorIndentGuide.background2": theme.background2,
            "editorIndentGuide.background3": theme.background2,
            "editorIndentGuide.background4": theme.background2,
            "editorIndentGuide.background5": theme.background2,
            "editorIndentGuide.background6": theme.background2,
            "editorInlayHint.background": theme.background2,
            "editorInlayHint.foreground": theme.dim,
            "editorInlayHint.parameterBackground": theme.background2,
            "editorInlayHint.parameterForeground": theme.dim,
            "editorInlayHint.typeBackground": theme.background2,
            "editorInlayHint.typeForeground": theme.dim,
            "editorLineNumber.activeForeground": theme.foreground,
            "editorLineNumber.dimmedForeground": theme.dim,
            "editorLineNumber.foreground": theme.dim,
            "editorPane.background": theme.background2,
            "editorRuler.foreground": theme.dim,
            "editorStickyScroll.background": theme.background,
            "editorStickyScroll.border": theme.border,
            "editorStickyScroll.shadow": theme.shadow,
            "editorStickyScrollHover.background": theme.hover,
            "editorUnicodeHighlight.background": theme.transparent,
            "editorUnicodeHighlight.border": theme.terminal.red,
            "extensionBadge.remoteBackground": theme.background2,
            "extensionBadge.remoteForeground": theme.foreground,
            "extensionButton.background": theme.background2,
            "extensionButton.foreground": theme.foreground,
            "extensionButton.hoverBackground": theme.hover,
            "extensionButton.prominentBackground": theme.background2,
            "extensionButton.prominentForeground": theme.foreground,
            "extensionButton.prominentHoverBackground": theme.hover,
            "extensionButton.separator": theme.border,
            "extensionIcon.preReleaseForeground": theme.terminal.cyan,
            "extensionIcon.sponsorForeground": theme.terminal.yellow,
            "extensionIcon.starForeground": theme.terminal.yellow,
            "extensionIcon.verifiedForeground": theme.terminal.green,
            "focusBorder": theme.transparent,
            "foreground": theme.foreground,
            "gitDecoration.addedResourceForeground": theme.terminal.green,
            "gitDecoration.conflictingResourceForeground": theme.terminal.magenta,
            "gitDecoration.deletedResourceForeground": theme.terminal.red,
            "gitDecoration.ignoredResourceForeground": theme.dim,
            "gitDecoration.modifiedResourceForeground": theme.terminal.yellow,
            "gitDecoration.renamedResourceForeground": theme.terminal.green,
            "gitDecoration.stageDeletedResourceForeground": theme.terminal.red,
            "gitDecoration.stageModifiedResourceForeground": theme.terminal.yellow,
            "gitDecoration.submoduleResourceForeground": theme.terminal.blue,
            "gitDecoration.untrackedResourceForeground": theme.terminal.green,
            "icon.foreground": theme.foreground,
            "input.background": theme.background,
            "input.border": theme.border,
            "input.foreground": theme.foreground,
            "input.placeholderForeground": theme.dim,
            "inputOption.activeBackground": theme.focus,
            "inputOption.activeBorder": theme.transparent,
            "inputOption.activeForeground": theme.foreground,
            "inputOption.hoverBackground": theme.hover,
            "keybindingLabel.background": theme.background2,
            "keybindingLabel.border": theme.border,
            "keybindingLabel.bottomBorder": theme.border,
            "keybindingLabel.foreground": theme.foreground,
            "keybindingTable.headerBackground": theme.focus,
            "keybindingTable.rowsBackground": theme.background2,

            "list.activeSelectionBackground": theme.focus,
            "list.activeSelectionForeground": theme.foreground,
            "list.activeSelectionIconForeground": theme.foreground,
            "list.highlightForeground": theme.foreground,
            "list.hoverBackground": theme.hover,
            "list.hoverForeground": theme.foreground,

            "list.inactiveSelectionBackground": theme.hover,
            "list.inactiveSelectionForeground": theme.foreground,
            "list.inactiveSelectionIconForeground": theme.foreground,
            "list.inactiveFocusBackground": theme.transparent,
            "list.inactiveFocusOutline": theme.transparent,

            "list.focusBackground": theme.transparent,
            "list.focusForeground": theme.foreground,
            "list.focusOutline": theme.foreground,
            "list.focusHighlightForeground": theme.foreground,

            "list.dropBackground": theme.focus,

            // "list.deemphasizedForeground": test,
            // "list.dropBetweenBackground": test,
            // "list.errorForeground": test,
            // "list.filterMatchBackground": test,
            // "list.filterMatchBorder": test,
            // "list.focusAndSelectionOutline": test,

            // "list.invalidItemForeground": test,
            // "list.warningForeground": test,

            // "listFilterWidget.background": test,
            // "listFilterWidget.noMatchesOutline": test,
            // "listFilterWidget.outline": test,
            // "listFilterWidget.shadow": test,

            "menu.background": theme.background,
            "menu.border": theme.border,
            "menu.foreground": theme.foreground,
            "menu.selectionBackground": theme.hover,
            "menu.selectionBorder": theme.transparent,
            "menu.selectionForeground": theme.foreground,
            "menu.separatorBackground": theme.border,
            "menubar.selectionBackground": theme.hover,
            "menubar.selectionBorder": theme.transparent,
            "menubar.selectionForeground": theme.foreground,
            "minimap.background": theme.transparent,
            "minimapSlider.activeBackground": theme.focus,
            "minimapSlider.background": theme.focus,
            "minimapSlider.hoverBackground": theme.hover,
            "notificationCenter.border": theme.border,
            "notificationCenterHeader.background": theme.focus,
            "notificationCenterHeader.foreground": theme.foreground,
            "notifications.background": theme.background,
            "notifications.border": theme.border,
            "notifications.foreground": theme.foreground,
            "outputView.background": theme.background,
            "outputViewStickyScroll.background": theme.background,
            "panel.background": theme.background,
            "panel.border": theme.border,
            "panel.dropBorder": theme.foreground,
            "panelInput.border": theme.border,
            "panelSection.border": theme.border,
            "panelSection.dropBackground": theme.focus,
            "panelSectionHeader.background": theme.background,
            "panelSectionHeader.border": theme.border,
            "panelSectionHeader.foreground": theme.foreground,
            "panelTitle.activeBorder": theme.foreground,
            "panelTitle.activeForeground": theme.foreground,
            "panelTitle.inactiveForeground": theme.dim,
            "peekView.border": theme.border,
            "peekViewEditor.background": theme.background2,
            "peekViewEditor.matchHighlightBackground": theme.focus,
            "peekViewEditor.matchHighlightBorder": theme.transparent,
            "peekViewEditorGutter.background": theme.background2,
            "peekViewEditorStickyScroll.background": theme.background2,
            "peekViewResult.background": theme.background2,
            "peekViewResult.fileForeground": theme.foreground,
            "peekViewResult.lineForeground": theme.foreground,
            "peekViewResult.matchHighlightBackground": theme.focus,
            "peekViewResult.selectionBackground": theme.focus,
            "peekViewResult.selectionForeground": theme.foreground,
            "peekViewTitle.background": theme.focus,
            "peekViewTitleDescription.foreground": theme.foreground,
            "peekViewTitleLabel.foreground": theme.foreground,
            "pickerGroup.border": theme.border,
            "pickerGroup.foreground": theme.foreground,
            "quickInput.background": theme.background,
            "quickInput.foreground": theme.foreground,
            "quickInputList.focusBackground": theme.focus,
            "quickInputList.focusForeground": theme.foreground,
            "quickInputList.focusIconForeground": theme.foreground,
            "scrollbar.shadow": theme.shadow,
            "scrollbarSlider.activeBackground": theme.focus,
            "scrollbarSlider.background": theme.hover,
            "scrollbarSlider.hoverBackground": theme.hover,
            "selection.background": theme.focus,
            "sideBar.background": theme.background2,
            "sideBar.border": theme.border,
            "sideBar.dropBackground": theme.focus,
            "sideBar.foreground": theme.foreground,
            "sideBarSectionHeader.background": theme.background2,
            "sideBarSectionHeader.border": theme.border,
            "sideBarSectionHeader.foreground": theme.foreground,
            "sideBarTitle.foreground": theme.foreground,
            "statusBar.background": theme.background2,
            "statusBar.border": theme.border,
            "statusBar.debuggingBackground": theme.focus,
            "statusBar.debuggingBorder": theme.focus,
            "statusBar.debuggingForeground": theme.foreground,
            "statusBar.focusBorder": theme.focus,
            "statusBar.foreground": theme.foreground,
            "statusBar.noFolderBackground": theme.background,
            "statusBar.noFolderBorder": theme.border,
            "statusBar.noFolderForeground": theme.foreground,
            "statusBarItem.activeBackground": theme.focus,
            "statusBarItem.compactHoverBackground": theme.hover,
            "statusBarItem.focusBorder": theme.focus,
            "statusBarItem.hoverBackground": theme.hover,
            "statusBarItem.hoverForeground": theme.foreground,
            "tab.activeBackground": theme.background,
            "tab.activeBorder": theme.transparent,
            "tab.activeBorderTop": theme.transparent,
            "tab.activeForeground": theme.foreground,
            "tab.activeModifiedBorder": theme.transparent,
            "tab.border": theme.border,
            "tab.dragAndDropBorder": theme.foreground,
            "tab.hoverBackground": theme.hover,
            "tab.hoverBorder": theme.transparent,
            "tab.hoverForeground": theme.foreground,
            "tab.inactiveBackground": theme.background2,
            "tab.inactiveForeground": theme.foreground,
            "tab.inactiveModifiedBorder": theme.transparent,
            "tab.lastPinnedBorder": theme.transparent,
            "tab.unfocusedActiveBackground": theme.transparent,
            "tab.unfocusedActiveBorder": theme.transparent,
            "tab.unfocusedActiveBorderTop": theme.transparent,
            "tab.unfocusedActiveForeground": theme.foreground,
            "tab.unfocusedActiveModifiedBorder": theme.transparent,
            "tab.unfocusedHoverBackground": theme.hover,
            "tab.unfocusedHoverBorder": theme.transparent,
            "tab.unfocusedHoverForeground": theme.foreground,
            "tab.unfocusedInactiveBackground": theme.transparent,
            "tab.unfocusedInactiveForeground": theme.foreground,
            "tab.unfocusedInactiveModifiedBorder": theme.transparent,
            "terminal.ansiBlack": theme.terminal.black,
            "terminal.ansiBlue": theme.terminal.blue,
            "terminal.ansiBrightBlack": theme.terminal.brightBlack,
            "terminal.ansiBrightBlue": theme.terminal.brightBlue,
            "terminal.ansiBrightCyan": theme.terminal.brightCyan,
            "terminal.ansiBrightGreen": theme.terminal.brightGreen,
            "terminal.ansiBrightMagenta": theme.terminal.brightMagenta,
            "terminal.ansiBrightRed": theme.terminal.brightRed,
            "terminal.ansiBrightWhite": theme.terminal.brightWhite,
            "terminal.ansiBrightYellow": theme.terminal.brightYellow,
            "terminal.ansiCyan": theme.terminal.cyan,
            "terminal.ansiGreen": theme.terminal.green,
            "terminal.ansiMagenta": theme.terminal.magenta,
            "terminal.ansiRed": theme.terminal.red,
            "terminal.ansiWhite": theme.terminal.white,
            "terminal.ansiYellow": theme.terminal.yellow,
            "terminal.background": theme.background,
            "terminal.border": theme.border,
            "terminal.dropBackground": theme.focus,
            "terminal.foreground": theme.foreground,
            "terminal.selectionBackground": theme.focus,
            "terminal.selectionForeground": theme.foreground,
            "terminal.tab.activeBorder": theme.transparent,
            "terminalCursor.background": theme.transparent,
            "terminalCursor.foreground": theme.foreground,
            "titleBar.activeBackground": theme.background2,
            "titleBar.activeForeground": theme.foreground,
            "titleBar.border": theme.border,
            "titleBar.inactiveBackground": theme.background2,
            "titleBar.inactiveForeground": theme.dim,
            "toolbar.activeBackground": theme.focus,
            "toolbar.hoverBackground": theme.hover,
            "toolbar.hoverOutline": theme.transparent,
            "widget.border": theme.border,
            "widget.shadow": theme.shadow,

            // "actionBar.toggledBackground": test,
            // "charts.blue": test,
            // "charts.foreground": test,
            // "charts.green": test,
            // "charts.lines": test,
            // "charts.orange": test,
            // "charts.purple": test,
            // "charts.red": test,
            // "charts.yellow": test,
            // "chat.avatarBackground": test,
            // "chat.avatarForeground": test,
            // "chat.requestBackground": test,
            // "chat.requestBorder": test,
            // "chat.slashCommandBackground": test,
            // "chat.slashCommandForeground": test,
            // "commentsView.resolvedIcon": test,
            // "commentsView.unresolvedIcon": test,
            // "contrastActiveBorder": test,
            // "contrastBorder": test,
            // "debugConsole.errorForeground": test,
            // "debugConsole.infoForeground": test,
            // "debugConsole.sourceForeground": test,
            // "debugConsole.warningForeground": test,
            // "debugConsoleInputIcon.foreground": test,
            // "debugExceptionWidget.background": test,
            // "debugExceptionWidget.border": test,
            // "debugIcon.breakpointCurrentStackframeForeground": test,
            // "debugIcon.breakpointDisabledForeground": test,
            // "debugIcon.breakpointForeground": test,
            // "debugIcon.breakpointStackframeForeground": test,
            // "debugIcon.breakpointUnverifiedForeground": test,
            // "debugIcon.continueForeground": test,
            // "debugIcon.disconnectForeground": test,
            // "debugIcon.pauseForeground": test,
            // "debugIcon.restartForeground": test,
            // "debugIcon.startForeground": test,
            // "debugIcon.stepBackForeground": test,
            // "debugIcon.stepIntoForeground": test,
            // "debugIcon.stepOutForeground": test,
            // "debugIcon.stepOverForeground": test,
            // "debugIcon.stopForeground": test,
            // "debugTokenExpression.boolean": test,
            // "debugTokenExpression.error": test,
            // "debugTokenExpression.name": test,
            // "debugTokenExpression.number": test,
            // "debugTokenExpression.string": test,
            // "debugTokenExpression.value": test,
            // "debugToolBar.background": test,
            // "debugToolBar.border": test,
            // "debugView.exceptionLabelBackground": test,
            // "debugView.exceptionLabelForeground": test,
            // "debugView.stateLabelBackground": test,
            // "debugView.stateLabelForeground": test,
            // "debugView.valueChangedHighlight": test,
            // "descriptionForeground": test,
            // "diffEditor.border": test,
            // "diffEditor.diagonalFill": test,
            // "diffEditor.insertedLineBackground": test,
            // "diffEditor.insertedTextBackground": test,
            // "diffEditor.insertedTextBorder": test,
            // "diffEditor.move.border": test,
            // "diffEditor.moveActive.border": test,
            // "diffEditor.removedLineBackground": test,
            // "diffEditor.removedTextBackground": test,
            // "diffEditor.removedTextBorder": test,
            // "diffEditor.unchangedCodeBackground": test,
            // "diffEditor.unchangedRegionBackground": test,
            // "diffEditor.unchangedRegionForeground": test,
            // "diffEditor.unchangedRegionShadow": test,
            // "diffEditorGutter.insertedLineBackground": test,
            // "diffEditorGutter.removedLineBackground": test,
            // "diffEditorOverview.insertedForeground": test,
            // "diffEditorOverview.removedForeground": test,
            // "disabledForeground": test,
            // "editor.findMatchBackground": test,
            // "editor.findMatchBorder": test,
            // "editor.findMatchHighlightBackground": test,
            // "editor.findMatchHighlightBorder": test,
            // "editor.findRangeHighlightBackground": test,
            // "editor.findRangeHighlightBorder": test,
            // "editor.focusedStackFrameHighlightBackground": test,
            // "editor.foldBackground": test,
            // "editor.hoverHighlightBackground": test,
            // "editor.inactiveSelectionBackground": test,
            // "editor.inlineValuesBackground": test,
            // "editor.inlineValuesForeground": test,
            // "editor.linkedEditingBackground": test,
            // "editor.rangeHighlightBackground": test,
            // "editor.rangeHighlightBorder": test,
            // "editor.snippetFinalTabstopHighlightBackground": test,
            // "editor.snippetFinalTabstopHighlightBorder": test,
            // "editor.snippetTabstopHighlightBackground": test,
            // "editor.snippetTabstopHighlightBorder": test,
            // "editor.stackFrameHighlightBackground": test,
            // "editor.symbolHighlightBackground": test,
            // "editor.symbolHighlightBorder": test,
            // "editor.wordHighlightBackground": test,
            // "editor.wordHighlightBorder": test,
            // "editor.wordHighlightStrongBackground": test,
            // "editor.wordHighlightStrongBorder": test,
            // "editor.wordHighlightTextBackground": test,
            // "editor.wordHighlightTextBorder": test,
            // "editorCodeLens.foreground": test,
            // "editorCommentsWidget.rangeActiveBackground": test,
            // "editorCommentsWidget.rangeBackground": test,
            // "editorCommentsWidget.replyInputBackground": test,
            // "editorCommentsWidget.resolvedBorder": test,
            // "editorCommentsWidget.unresolvedBorder": test,
            // "editorError.background": test,
            // "editorError.border": test,
            // "editorError.foreground": test,
            // "editorGhostText.background": test,
            // "editorGhostText.border": test,
            // "editorGhostText.foreground": test,
            // "editorGroup.dropIntoPromptBackground": test,
            // "editorGroup.dropIntoPromptBorder": test,
            // "editorGroup.dropIntoPromptForeground": test,
            // "editorGroup.focusedEmptyBorder": test,
            // "editorGutter.commentGlyphForeground": test,
            // "editorGutter.commentRangeForeground": test,
            // "editorGutter.commentUnresolvedGlyphForeground": test,
            // "editorHint.border": test,
            // "editorHint.foreground": test,
            // "editorHoverWidget.background": test,
            // "editorHoverWidget.border": test,
            // "editorHoverWidget.foreground": test,
            // "editorHoverWidget.highlightForeground": test,
            // "editorHoverWidget.statusBarBackground": test,
            // "editorInfo.background": test,
            // "editorInfo.border": test,
            // "editorInfo.foreground": test,
            // "editorLightBulb.foreground": test,
            // "editorLightBulbAi.foreground": test,
            // "editorLightBulbAutoFix.foreground": test,
            // "editorLink.activeForeground": test,
            // "editorMarkerNavigation.background": test,
            // "editorMarkerNavigationError.background": test,
            // "editorMarkerNavigationError.headerBackground": test,
            // "editorMarkerNavigationInfo.background": test,
            // "editorMarkerNavigationInfo.headerBackground": test,
            // "editorMarkerNavigationWarning.background": test,
            // "editorMarkerNavigationWarning.headerBackground": test,
            // "editorOverviewRuler.addedForeground": test,
            // "editorOverviewRuler.background": test,
            // "editorOverviewRuler.border": test,
            // "editorOverviewRuler.bracketMatchForeground": test,
            // "editorOverviewRuler.commentForeground": test,
            // "editorOverviewRuler.commentUnresolvedForeground": test,
            // "editorOverviewRuler.commonContentForeground": test,
            // "editorOverviewRuler.currentContentForeground": test,
            // "editorOverviewRuler.deletedForeground": test,
            // "editorOverviewRuler.errorForeground": test,
            // "editorOverviewRuler.findMatchForeground": test,
            // "editorOverviewRuler.incomingContentForeground": test,
            // "editorOverviewRuler.infoForeground": test,
            // "editorOverviewRuler.inlineChatInserted": test,
            // "editorOverviewRuler.inlineChatRemoved": test,
            // "editorOverviewRuler.modifiedForeground": test,
            // "editorOverviewRuler.rangeHighlightForeground": test,
            // "editorOverviewRuler.selectionHighlightForeground": test,
            // "editorOverviewRuler.warningForeground": test,
            // "editorOverviewRuler.wordHighlightForeground": test,
            // "editorOverviewRuler.wordHighlightStrongForeground": test,
            // "editorOverviewRuler.wordHighlightTextForeground": test,
            // "editorSuggestWidget.background": test,
            // "editorSuggestWidget.border": test,
            // "editorSuggestWidget.focusHighlightForeground": test,
            // "editorSuggestWidget.foreground": test,
            // "editorSuggestWidget.highlightForeground": test,
            // "editorSuggestWidget.selectedBackground": test,
            // "editorSuggestWidget.selectedForeground": test,
            // "editorSuggestWidget.selectedIconForeground": test,
            // "editorSuggestWidgetStatus.foreground": test,
            // "editorUnnecessaryCode.border": test,
            // "editorUnnecessaryCode.opacity": test,
            // "editorWarning.background": test,
            // "editorWarning.border": test,
            // "editorWarning.foreground": test,
            // "editorWatermark.foreground": test,
            // "editorWhitespace.foreground": test,
            // "editorWidget.background": test,
            // "editorWidget.border": test,
            // "editorWidget.foreground": test,
            // "editorWidget.resizeBorder": test,
            // "errorForeground": test,
            // "inlineChat.background": test,
            // "inlineChat.border": test,
            // "inlineChat.regionHighlight": test,
            // "inlineChat.shadow": test,
            // "inlineChatDiff.inserted": test,
            // "inlineChatDiff.removed": test,
            // "inlineChatInput.background": test,
            // "inlineChatInput.border": test,
            // "inlineChatInput.focusBorder": test,
            // "inlineChatInput.placeholderForeground": test,
            // "inputValidation.errorBackground": test,
            // "inputValidation.errorBorder": test,
            // "inputValidation.errorForeground": test,
            // "inputValidation.infoBackground": test,
            // "inputValidation.infoBorder": test,
            // "inputValidation.infoForeground": test,
            // "inputValidation.warningBackground": test,
            // "inputValidation.warningBorder": test,
            // "inputValidation.warningForeground": test,
            // "interactive.activeCodeBorder": test,
            // "interactive.inactiveCodeBorder": test,
            // "merge.border": test,
            // "merge.commonContentBackground": test,
            // "merge.commonHeaderBackground": test,
            // "merge.currentContentBackground": test,
            // "merge.currentHeaderBackground": test,
            // "merge.incomingContentBackground": test,
            // "merge.incomingHeaderBackground": test,
            // "mergeEditor.change.background": test,
            // "mergeEditor.change.word.background": test,
            // "mergeEditor.changeBase.background": test,
            // "mergeEditor.changeBase.word.background": test,
            // "mergeEditor.conflict.handled.minimapOverViewRuler": test,
            // "mergeEditor.conflict.handledFocused.border": test,
            // "mergeEditor.conflict.handledUnfocused.border": test,
            // "mergeEditor.conflict.input1.background": test,
            // "mergeEditor.conflict.input2.background": test,
            // "mergeEditor.conflict.unhandled.minimapOverViewRuler": test,
            // "mergeEditor.conflict.unhandledFocused.border": test,
            // "mergeEditor.conflict.unhandledUnfocused.border": test,
            // "mergeEditor.conflictingLines.background": test,
            // "minimap.errorHighlight": test,
            // "minimap.findMatchHighlight": test,
            // "minimap.foregroundOpacity": test,
            // "minimap.infoHighlight": test,
            // "minimap.selectionHighlight": test,
            // "minimap.selectionOccurrenceHighlight": test,
            // "minimap.warningHighlight": test,
            // "minimapGutter.addedBackground": test,
            // "minimapGutter.deletedBackground": test,
            // "minimapGutter.modifiedBackground": test,
            // "multiDiffEditor.background": test,
            // "multiDiffEditor.border": test,
            // "multiDiffEditor.headerBackground": test,
            // "notebook.cellBorderColor": test,
            // "notebook.cellEditorBackground": test,
            // "notebook.cellHoverBackground": test,
            // "notebook.cellInsertionIndicator": test,
            // "notebook.cellStatusBarItemHoverBackground": test,
            // "notebook.cellToolbarSeparator": test,
            // "notebook.editorBackground": test,
            // "notebook.focusedCellBackground": test,
            // "notebook.focusedCellBorder": test,
            // "notebook.focusedEditorBorder": test,
            // "notebook.inactiveFocusedCellBorder": test,
            // "notebook.inactiveSelectedCellBorder": test,
            // "notebook.outputContainerBackgroundColor": test,
            // "notebook.outputContainerBorderColor": test,
            // "notebook.selectedCellBackground": test,
            // "notebook.selectedCellBorder": test,
            // "notebook.symbolHighlightBackground": test,
            // "notebookEditorOverviewRuler.runningCellForeground": test,
            // "notebookScrollbarSlider.activeBackground": test,
            // "notebookScrollbarSlider.background": test,
            // "notebookScrollbarSlider.hoverBackground": test,
            // "notebookStatusErrorIcon.foreground": test,
            // "notebookStatusRunningIcon.foreground": test,
            // "notebookStatusSuccessIcon.foreground": test,
            // "notificationLink.foreground": test,
            // "notificationsErrorIcon.foreground": test,
            // "notificationsInfoIcon.foreground": test,
            // "notificationsWarningIcon.foreground": test,
            // "notificationToast.border": test,
            // "ports.iconRunningProcessForeground": test,
            // "problemsErrorIcon.foreground": test,
            // "problemsInfoIcon.foreground": test,
            // "problemsWarningIcon.foreground": test,
            // "profileBadge.background": test,
            // "profileBadge.foreground": test,
            // "progressBar.background": test,
            // "quickInput.list.focusBackground": test,
            // "quickInputTitle.background": test,
            // "sash.hoverBorder": test,
            // "scm.historyItemAdditionsForeground": test,
            // "scm.historyItemDeletionsForeground": test,
            // "scm.historyItemSelectedStatisticsBorder": test,
            // "scm.historyItemStatisticsBorder": test,
            // "search.resultsInfoForeground": test,
            // "searchEditor.findMatchBackground": test,
            // "searchEditor.findMatchBorder": test,
            // "searchEditor.textInputBorder": test,
            // "settings.checkboxBackground": test,
            // "settings.checkboxBorder": test,
            // "settings.checkboxForeground": test,
            // "settings.dropdownBackground": test,
            // "settings.dropdownBorder": test,
            // "settings.dropdownForeground": test,
            // "settings.dropdownListBorder": test,
            // "settings.focusedRowBackground": test,
            // "settings.focusedRowBorder": test,
            // "settings.headerBorder": test,
            // "settings.headerForeground": test,
            // "settings.modifiedItemIndicator": test,
            // "settings.numberInputBackground": test,
            // "settings.numberInputBorder": test,
            // "settings.numberInputForeground": test,
            // "settings.rowHoverBackground": test,
            // "settings.sashBorder": test,
            // "settings.settingsHeaderHoverForeground": test,
            // "settings.textInputBackground": test,
            // "settings.textInputBorder": test,
            // "settings.textInputForeground": test,
            // "sideBySideEditor.horizontalBorder": test,
            // "sideBySideEditor.verticalBorder": test,
            // "simpleFindWidget.sashBorder": test,
            // "statusBarItem.errorBackground": test,
            // "statusBarItem.errorForeground": test,
            // "statusBarItem.errorHoverBackground": test,
            // "statusBarItem.errorHoverForeground": test,
            // "statusBarItem.offlineBackground": test,
            // "statusBarItem.offlineForeground": test,
            // "statusBarItem.offlineHoverBackground": test,
            // "statusBarItem.offlineHoverForeground": test,
            // "statusBarItem.prominentBackground": test,
            // "statusBarItem.prominentForeground": test,
            // "statusBarItem.prominentHoverBackground": test,
            // "statusBarItem.prominentHoverForeground": test,
            // "statusBarItem.remoteBackground": test,
            // "statusBarItem.remoteForeground": test,
            // "statusBarItem.remoteHoverBackground": test,
            // "statusBarItem.remoteHoverForeground": test,
            // "statusBarItem.warningBackground": test,
            // "statusBarItem.warningForeground": test,
            // "statusBarItem.warningHoverBackground": test,
            // "statusBarItem.warningHoverForeground": test,
            // "symbolIcon.arrayForeground": test,
            // "symbolIcon.booleanForeground": test,
            // "symbolIcon.classForeground": test,
            // "symbolIcon.colorForeground": test,
            // "symbolIcon.constantForeground": test,
            // "symbolIcon.constructorForeground": test,
            // "symbolIcon.enumeratorForeground": test,
            // "symbolIcon.enumeratorMemberForeground": test,
            // "symbolIcon.eventForeground": test,
            // "symbolIcon.fieldForeground": test,
            // "symbolIcon.fileForeground": test,
            // "symbolIcon.folderForeground": test,
            // "symbolIcon.functionForeground": test,
            // "symbolIcon.interfaceForeground": test,
            // "symbolIcon.keyForeground": test,
            // "symbolIcon.keywordForeground": test,
            // "symbolIcon.methodForeground": test,
            // "symbolIcon.moduleForeground": test,
            // "symbolIcon.namespaceForeground": test,
            // "symbolIcon.nullForeground": test,
            // "symbolIcon.numberForeground": test,
            // "symbolIcon.objectForeground": test,
            // "symbolIcon.operatorForeground": test,
            // "symbolIcon.packageForeground": test,
            // "symbolIcon.propertyForeground": test,
            // "symbolIcon.referenceForeground": test,
            // "symbolIcon.snippetForeground": test,
            // "symbolIcon.stringForeground": test,
            // "symbolIcon.structForeground": test,
            // "symbolIcon.textForeground": test,
            // "symbolIcon.typeParameterForeground": test,
            // "symbolIcon.unitForeground": test,
            // "symbolIcon.variableForeground": test,
            // "terminal.findMatchBackground": test,
            // "terminal.findMatchBorder": test,
            // "terminal.findMatchHighlightBackground": test,
            // "terminal.findMatchHighlightBorder": test,
            // "terminal.hoverHighlightBackground": test,
            // "terminal.inactiveSelectionBackground": test,
            // "terminalCommandDecoration.defaultBackground": test,
            // "terminalCommandDecoration.errorBackground": test,
            // "terminalCommandDecoration.successBackground": test,
            // "terminalOverviewRuler.cursorForeground": test,
            // "terminalOverviewRuler.findMatchForeground": test,
            // "terminalStickyScroll.background": test,
            // "terminalStickyScrollHover.background": test,
            // "testing.coverCountBadgeBackground": test,
            // "testing.coverCountBadgeForeground": test,
            // "testing.coveredBackground": test,
            // "testing.coveredBorder": test,
            // "testing.coveredGutterBackground": test,
            // "testing.iconErrored": test,
            // "testing.iconFailed": test,
            // "testing.iconPassed": test,
            // "testing.iconQueued": test,
            // "testing.iconSkipped": test,
            // "testing.iconUnset": test,
            // "testing.message.error.decorationForeground": test,
            // "testing.message.error.lineBackground": test,
            // "testing.message.info.decorationForeground": test,
            // "testing.message.info.lineBackground": test,
            // "testing.messagePeekBorder": test,
            // "testing.messagePeekHeaderBackground": test,
            // "testing.peekBorder": test,
            // "testing.peekHeaderBackground": test,
            // "testing.runAction": test,
            // "testing.uncoveredBackground": test,
            // "testing.uncoveredBorder": test,
            // "testing.uncoveredBranchBackground": test,
            // "testing.uncoveredGutterBackground": test,
            // "textBlockQuote.background": test,
            // "textBlockQuote.border": test,
            // "textCodeBlock.background": test,
            // "textLink.activeForeground": test,
            // "textLink.foreground": test,
            // "textPreformat.background": test,
            // "textPreformat.foreground": test,
            // "textSeparator.foreground": test,
            // "tree.inactiveIndentGuidesStroke": test,
            // "tree.indentGuidesStroke": test,
            // "tree.tableColumnsBorder": test,
            // "tree.tableOddRowsBackground": test,
            // "walkThrough.embeddedEditorBackground": test,
            // "walkthrough.stepTitle.foreground": test,
            // "welcomePage.background": test,
            // "welcomePage.progress.background": test,
            // "welcomePage.progress.foreground": test,
            // "welcomePage.tileBackground": test,
            // "welcomePage.tileBorder": test,
            // "welcomePage.tileHoverBackground": test,
            // "window.activeBorder": test,
            // "window.inactiveBorder": test,
        },
        // https://macromates.com/manual/en/language_grammars
        // https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
        // https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide
        // https://tailwindcss.com/docs/customizing-colors
        tokenColors: [
            { scope: ["strong", "markup.bold", "markup.heading"], settings: { fontStyle: "bold" } },
            { scope: ["emphasis, markup.italic"], settings: { fontStyle: "italic" } },
            { scope: ["markup.underline"], settings: { fontStyle: "underline" } },
            { scope: ["markup.strikethrough"], settings: { fontStyle: "strikethrough" } },
            { scope: ["markup.inserted"], settings: { foreground: tw.green[theme.scale] } },
            { scope: ["markup.deleted"], settings: { foreground: tw.red[theme.scale] } },
            { scope: ["markup.changed"], settings: { foreground: tw.yellow[theme.scale] } },
            {
                scope: ["comment", "comment.block", "comment.block.documentation", "comment.line"],
                settings: {
                    foreground: theme.comment,
                },
            },
            {
                scope: [
                    "constant",
                    "constant.character",
                    "constant.character.escape",
                    "constant.other",
                    "constant.regexp",
                    "constant.rgb-value",
                ],
                settings: {
                    foreground: tw.yellow[theme.scale],
                },
            },
            {
                scope: [
                    "constant.numeric",
                    "constant.numeric.integer",
                    "constant.numeric.float",
                    "constant.numeric.hex",
                    "constant.numeric.octal",
                ],
                settings: {
                    foreground: tw.purple[theme.scale],
                },
            },
            {
                scope: [
                    "entity",
                    "entity.name",
                    "entity.name.class",
                    "entity.name.function",
                    "entity.name.method",
                    "entity.name.section",
                    "entity.name.selector",
                    "entity.name.tag",
                    "entity.name.type",
                    "entity.other",
                    "entity.other.attribute-name",
                    "entity.other.inherited-class",
                    "punctuation.definition.heading",
                ],
                settings: {
                    foreground: tw.fuchsia[theme.scale],
                },
            },
            {
                scope: ["invalid", "invalid.deprecated", "invalid.illegal"],
                settings: {
                    foreground: tw.red[theme.scale],
                },
            },
            {
                scope: ["keyword", "keyword.control", "keyword.other", "string.json"],
                settings: {
                    foreground: tw.rose[theme.scale],
                },
            },
            {
                scope: [
                    "keyword.operator",
                    "keyword.operator.new",
                    "keyword.operator.assignment",
                    "keyword.operator.arithmetic",
                    "keyword.operator.logical",
                ],
                settings: {
                    foreground: tw.neutral[theme.scale],
                },
            },
            {
                scope: [
                    "meta",
                    "meta.block",
                    "meta.cast",
                    "meta.class",
                    "meta.function",
                    "meta.function-call",
                    "meta.preprocessor",
                    "meta.return-type",
                    "meta.selector",
                    "meta.tag",
                    "meta.type.annotation",
                    "meta.type",
                ],
                settings: {
                    foreground: tw.indigo[theme.scale],
                },
            },
            {
                scope: [
                    "punctuation",
                    "punctuation.definition.string.begin",
                    "punctuation.definition.string.end",
                    "punctuation.separator",
                    "punctuation.separator.continuation",
                    "punctuation.terminator",
                ],
                settings: {
                    foreground: tw.neutral[theme.scale],
                },
            },
            {
                scope: ["storage", "storage.modifier", "storage.type"],
                settings: {
                    foreground: tw.green[theme.scale],
                },
            },
            {
                scope: [
                    "string",
                    "string.interpolated",
                    "string.other",
                    "string.quoted",
                    "string.quoted.double",
                    "string.quoted.other",
                    "string.quoted.single",
                    "string.quoted.triple",
                    "string.regexp",
                    "string.unquoted",
                ],
                settings: {
                    foreground: tw.sky[theme.scale],
                },
            },
            {
                scope: [
                    "support",
                    "support.class",
                    "support.constant",
                    "support.function",
                    "support.other",
                    "support.type",
                    "support.type.property-name",
                    "support.variable",
                ],
                settings: {
                    foreground: tw.amber[theme.scale],
                },
            },
            {
                scope: [
                    "variable",
                    "variable.language",
                    "variable.name",
                    "variable.other",
                    "variable.other.readwrite",
                    "variable.parameter",
                ],
                settings: {
                    foreground: tw.blue[theme.scale],
                },
            },
        ],
        semanticTokenColors: {
            newOperator: tw.purple[theme.scale],
            stringLiteral: tw.red[theme.scale],
            customLiteral: tw.yellow[theme.scale],
            numberLiteral: tw.emerald[theme.scale],
        },
    };
};
